export const LOAD_BLOGS_SUCESS = 'LOAD_BLOGS_SUCESS';
export const LOAD_BLOG_DETAIL_SUCESS = 'LOAD_BLOG_DETAIL_SUCESS';

export const LOAD_PRODUCTS_SUCESS = 'LOAD_PRODUCTS_SUCESS';
export const LOAD_PRODUCT_DETAIL_SUCESS = 'LOAD_PRODUCT_DETAIL_SUCESS';
export const LOAD_CATEGORIES_SUCESS = 'LOAD_CATEGORIES_SUCESS';
export const LOAD_RELATED_PRODUCTS_SUCESS = 'LOAD_RELATED_PRODUCTS_SUCESS';
export const LOAD_LATEST_PRODUCTS_SUCESS = 'LOAD_LATEST_PRODUCTS_SUCESS';
export const LOAD_SPECIAL_PRODUCTS_SUCESS = 'LOAD_SPECIAL_PRODUCTS_SUCESS';
export const LOAD_BESTSELLER_PRODUCTS_SUCESS = 'LOAD_BESTSELLER_PRODUCTS_SUCESS';

export const LOAD_SHOPING_CART_SUCESS = 'LOAD_SHOPING_CART_SUCESS';
export const ADD_SHOPING_CART_ITEM = 'ADD_SHOPING_CART_ITEM';
export const REMOVE_SHOPING_CART_ITEM = 'REMOVE_SHOPING_CART';
export const UPDATE_SHOPING_CART_ITEM = 'UPDATE_SHOPING_CART';

export const ACCOUNT_LOGIN_SUCESS = 'ACCOUNT_LOGIN_SUCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';
export const ACCOUNT_REGISTER_SUCESS = 'ACCOUNT_REGISTER_SUCESS';

export const LOAD_BLOG_CATEGORIES_SUCCESS = 'LOAD_BLOG_CATEGORIES_SUCCESS';
