export const LOAD_ADMIN_PRODUCTS_SUCESS = 'LOAD_ADMIN_PRODUCTS_SUCESS';
export const ADD_ADMIN_PRODUCTS_SUCESS = 'ADD_ADMIN_PRODUCTS_SUCESS';
export const UPDATE_ADMIN_PRODUCTS_SUCCESS = 'UPDATE_ADMIN_PRODUCTS_SUCCESS';
export const UPDATE_ADMIN_BRANDS_SUCCESS = 'UPDATE_ADMIN_BRANDS_SUCCESS';

export const LOAD_ADMIN_PRODUCTS_FAILURE = 'LOAD_ADMIN_PRODUCTS_FAILURE';
export const ADD_ADMIN_PRODUCTS_FAILURE = 'ADD_ADMIN_PRODUCTS_FAILURE';
export const UPDATE_ADMIN_PRODUCTS_FAILURE = 'UPDATE_ADMIN_PRODUCTS_FAILURE';
export const UPDATE_ADMIN_BRANDS_FAILURE = 'UPDATE_ADMIN_BRANDS_FAILURE';
