export const LOAD_ADMIN_PRODUCTS_SUCESS = 'LOAD_ADMIN_PRODUCTS_SUCESS';
export const ADD_ADMIN_PRODUCTS_SUCESS = 'ADD_ADMIN_PRODUCTS_SUCESS';
export const LOAD_ADMIN_PRODUCTS_FAILURE = 'LOAD_ADMIN_PRODUCTS_FAILURE';
export const ADD_ADMIN_PRODUCTS_FAILURE = 'ADD_ADMIN_PRODUCTS_FAILURE';
